import type { StudentProfile } from "../models/studentProfile";

export const sampleStudents: StudentProfile[] = [
  {
    studentId: "12004567",
    currentGrade: 12,
    currentCourses: ["CALCULUS", "ENG_11"],
    currentAPs: ["AP_CSP", "AP_CALC_AB"],
    strengths: ["Coding", "Science"],
    weaknesses: ["Math"],
    interests: ["FinTech", "AI", "Computer Science"],
    careerGoals: ["AI Engineer", "FinTech Product Builder"],
    goalClarity: "High",
    workloadTolerance: "High",
    riskPreference: "Balanced",
    scholarshipImportance: "High",
    mainCountry: "UAE",
    additionalCountries: ["Qatar", "US"],
    countryIntent: "main_focus",
    targetCountries: ["UAE", "Qatar", "US"],
    futurePlans: "Study CS/AI and work in applied finance technology.",
    preferencesToAvoid: ["low-rigor plans"],
    preferences: ["project-based", "applied technology"],
    selfReportedAcademicConfidence: "Medium",
    desiredCourseYear: "Now",
    priorityStyle: "strongest_path",
    optimizationTarget: "career_alignment",
  },
  {
    studentId: "12004568",
    currentGrade: 11,
    currentCourses: ["MATH_INT_3", "ENG_11"],
    currentAPs: [],
    strengths: ["Writing", "Humanities"],
    weaknesses: ["Science"],
    interests: ["Business", "Economics", "Communication"],
    careerGoals: ["Business Management", "Marketing"],
    goalClarity: "Medium",
    workloadTolerance: "Medium",
    riskPreference: "Avoid risk",
    scholarshipImportance: "Medium",
    mainCountry: "UAE",
    additionalCountries: ["Jordan"],
    countryIntent: "keep_options_open",
    targetCountries: ["UAE", "Jordan"],
    futurePlans: "Business degree with practical internships.",
    preferencesToAvoid: ["heavy lab load"],
    preferences: ["balanced workload"],
    selfReportedAcademicConfidence: "Medium",
    desiredCourseYear: "Now",
    priorityStyle: "balanced_path",
    optimizationTarget: "higher_grades",
  },
  {
    studentId: "12004569",
    currentGrade: 10,
    currentCourses: ["MATH_INT_2", "CHEM_10", "VPA"],
    currentAPs: [],
    strengths: ["Arts"],
    weaknesses: ["Math"],
    interests: ["Design", "Creative Media"],
    careerGoals: ["Creative Direction"],
    goalClarity: "High",
    workloadTolerance: "Low",
    riskPreference: "Avoid risk",
    scholarshipImportance: "Low",
    mainCountry: "UAE",
    additionalCountries: [],
    countryIntent: "unsure",
    targetCountries: ["UAE"],
    futurePlans: "Creative major with portfolio focus.",
    preferencesToAvoid: ["very heavy exam pressure"],
    preferences: ["creative and applied courses"],
    selfReportedAcademicConfidence: "Medium",
    desiredCourseYear: "Now",
    priorityStyle: "not_sure",
    optimizationTarget: "keeping_options_open",
  },
];

