import type { ScenarioAdjustments } from "@/lib/domain/models/session";
import type { StudentProfile } from "@/lib/domain/models/studentProfile";

/**
 * SYNTHETIC TEST DATA ONLY.
 *
 * These invented profiles contain no names, contact details, school identifiers,
 * or production persistence hooks. They are imported only by unit tests.
 */

export interface RecommendationFixture {
  name: string;
  profile: StudentProfile;
  scenario: ScenarioAdjustments;
}

const semester1: ScenarioAdjustments = {
  semester: "Semester1",
  isMidYear: false,
};

const semester2: ScenarioAdjustments = {
  semester: "Semester2",
  isMidYear: true,
};

function syntheticProfile(studentId: string, overrides: Partial<StudentProfile>): StudentProfile {
  return {
    studentId,
    currentGrade: 12,
    currentCourses: [],
    currentAPs: [],
    mainCountry: "UAE",
    additionalCountries: [],
    countryIntent: "keep_options_open",
    strengths: [],
    weaknesses: [],
    interests: [],
    careerGoals: [],
    goalClarity: "Medium",
    workloadTolerance: "Medium",
    riskPreference: "Balanced",
    scholarshipImportance: "Medium",
    futurePlans: "",
    preferencesToAvoid: [],
    preferences: [],
    selfReportedAcademicConfidence: "Medium",
    desiredCourseYear: "Now",
    priorityStyle: "balanced_path",
    optimizationTarget: "keeping_options_open",
    ...overrides,
  };
}

export const recommendationFixtures = {
  highStemGrade12Semester1: {
    name: "high-STEM Grade 12 Semester 1",
    profile: syntheticProfile("SYNTHETIC-HIGH-STEM", {
      strengths: ["Math", "Science"],
      interests: ["engineering", "physics", "robotics"],
      careerGoals: ["mechanical engineering"],
      goalClarity: "High",
      workloadTolerance: "High",
      riskPreference: "Embrace stretch",
      scholarshipImportance: "High",
      futurePlans: "Explore an engineering degree through rigorous quantitative courses.",
      preferences: ["lab work", "quantitative projects"],
      selfReportedAcademicConfidence: "High",
      priorityStyle: "strongest_path",
      optimizationTarget: "university_competitiveness",
    }),
    scenario: semester1,
  },
  computerScienceFocused: {
    name: "computer-science-focused student",
    profile: syntheticProfile("SYNTHETIC-CS-FOCUS", {
      strengths: ["Coding", "Math"],
      interests: ["computer science", "software", "AI", "data"],
      careerGoals: ["software engineering"],
      goalClarity: "High",
      workloadTolerance: "High",
      riskPreference: "Balanced",
      scholarshipImportance: "High",
      futurePlans: "Study computer science and build applied software.",
      preferences: ["project-based technology"],
      selfReportedAcademicConfidence: "High",
      priorityStyle: "strongest_path",
      optimizationTarget: "career_alignment",
    }),
    scenario: semester1,
  },
  businessGrade12Semester1: {
    name: "business-focused Grade 12 Semester 1",
    profile: syntheticProfile("SYNTHETIC-BUSINESS", {
      strengths: ["Humanities", "English"],
      interests: ["business", "finance", "economics", "marketing"],
      careerGoals: ["business management"],
      goalClarity: "High",
      workloadTolerance: "Medium",
      riskPreference: "Avoid risk",
      futurePlans: "Study business with applied finance and communication.",
      preferencesToAvoid: ["very heavy lab workload"],
      preferences: ["applied projects"],
      priorityStyle: "safest_highest_grade",
      optimizationTarget: "career_alignment",
    }),
    scenario: semester1,
  },
  humanitiesGrade11: {
    name: "humanities-focused Grade 11",
    profile: syntheticProfile("SYNTHETIC-HUMANITIES", {
      currentGrade: 11,
      strengths: ["English", "Humanities"],
      weaknesses: ["Math"],
      interests: ["history", "writing", "law", "communication"],
      careerGoals: ["law"],
      goalClarity: "High",
      workloadTolerance: "Medium",
      riskPreference: "Balanced",
      mainCountry: "Jordan",
      countryIntent: "main_focus",
      futurePlans: "Explore law and writing-intensive university pathways.",
      selfReportedAcademicConfidence: "Medium",
      priorityStyle: "balanced_path",
      optimizationTarget: "career_alignment",
    }),
    scenario: semester1,
  },
  highWorkloadTolerance: {
    name: "high-workload-tolerance student",
    profile: syntheticProfile("SYNTHETIC-HIGH-WORKLOAD", {
      currentGrade: 11,
      strengths: ["Math", "Science", "Coding"],
      interests: ["science", "coding", "research"],
      careerGoals: ["engineering research"],
      goalClarity: "Medium",
      workloadTolerance: "High",
      riskPreference: "Embrace stretch",
      scholarshipImportance: "High",
      selfReportedAcademicConfidence: "High",
      priorityStyle: "strongest_path",
      optimizationTarget: "university_competitiveness",
    }),
    scenario: semester1,
  },
  lowWorkloadTolerance: {
    name: "low-workload-tolerance student",
    profile: syntheticProfile("SYNTHETIC-LOW-WORKLOAD", {
      currentGrade: 11,
      strengths: ["Arts", "English"],
      weaknesses: ["Math", "Science"],
      interests: ["design", "writing"],
      careerGoals: ["creative direction"],
      goalClarity: "Medium",
      workloadTolerance: "Low",
      riskPreference: "Avoid risk",
      scholarshipImportance: "Low",
      preferencesToAvoid: ["heavy homework", "lab intensity"],
      preferences: ["creative projects"],
      selfReportedAcademicConfidence: "Low",
      priorityStyle: "safest_highest_grade",
      optimizationTarget: "lighter_workload",
    }),
    scenario: semester1,
  },
  missingOptionalAnswers: {
    name: "student with missing optional answers",
    profile: syntheticProfile("SYNTHETIC-MISSING-OPTIONAL", {
      currentGrade: 11,
      strengths: [],
      weaknesses: [],
      interests: [],
      careerGoals: [],
      goalClarity: "Low",
      additionalCountries: [],
      countryIntent: "unsure",
      futurePlans: "",
      preferencesToAvoid: [],
      preferences: [],
      selfReportedAcademicConfidence: "Medium",
      priorityStyle: undefined,
      optimizationTarget: undefined,
      targetCountries: undefined,
    }),
    scenario: semester1,
  },
  conflictingGoals: {
    name: "student with conflicting goals",
    profile: syntheticProfile("SYNTHETIC-CONFLICTING-GOALS", {
      strengths: ["Math", "Arts"],
      weaknesses: ["Science"],
      interests: ["engineering", "painting", "marketing"],
      careerGoals: ["medicine", "creative business"],
      goalClarity: "Low",
      workloadTolerance: "High",
      riskPreference: "Avoid risk",
      scholarshipImportance: "High",
      futurePlans: "Keep medicine, design, and business options open.",
      preferencesToAvoid: ["heavy lab work"],
      preferences: ["hands-on projects"],
      selfReportedAcademicConfidence: "Low",
      priorityStyle: "strongest_path",
      optimizationTarget: "keeping_options_open",
    }),
    scenario: semester1,
  },
  prerequisiteBoundary: {
    name: "prerequisite-boundary student",
    profile: syntheticProfile("SYNTHETIC-PREREQ-BOUNDARY", {
      strengths: ["Science"],
      weaknesses: ["Math"],
      interests: ["medicine", "chemistry"],
      careerGoals: ["medicine"],
      goalClarity: "High",
      workloadTolerance: "Medium",
      riskPreference: "Balanced",
      scholarshipImportance: "High",
      currentCourses: [],
      currentAPs: [],
      futurePlans: "Explore medicine without any recorded prerequisite coursework.",
      selfReportedAcademicConfidence: "Medium",
      priorityStyle: "strongest_path",
      optimizationTarget: "career_alignment",
    }),
    scenario: semester1,
  },
  fewValidPlansGrade12Semester2: {
    name: "few-valid-plan Grade 12 Semester 2",
    profile: syntheticProfile("SYNTHETIC-ONE-VALID-PLAN", {
      currentCourses: ["ENV_SCI"],
      currentAPs: ["AP_CALC_AB", "AP_CHEM", "AP_BIO"],
      strengths: ["Math", "Science"],
      interests: ["medicine", "biology"],
      careerGoals: ["medicine"],
      goalClarity: "High",
      workloadTolerance: "High",
      riskPreference: "Embrace stretch",
      scholarshipImportance: "High",
      futurePlans: "Continue the same invented year-long selections in Semester 2.",
      selfReportedAcademicConfidence: "High",
      priorityStyle: "strongest_path",
      optimizationTarget: "university_competitiveness",
      desiredCourseYear: "Next",
    }),
    scenario: semester2,
  },
  tieHeavyGrade12Semester2: {
    name: "tie-heavy Grade 12 Semester 2",
    profile: syntheticProfile("SYNTHETIC-TIE-HEAVY", {
      strengths: [],
      weaknesses: [],
      interests: [],
      careerGoals: [],
      goalClarity: "Low",
      workloadTolerance: "Medium",
      riskPreference: "Balanced",
      scholarshipImportance: "Low",
      countryIntent: "unsure",
      futurePlans: "",
      preferencesToAvoid: [],
      preferences: [],
      selfReportedAcademicConfidence: "Medium",
      priorityStyle: "not_sure",
      optimizationTarget: "keeping_options_open",
      desiredCourseYear: "Next",
    }),
    scenario: semester2,
  },
} satisfies Record<string, RecommendationFixture>;
